name: LLM Papers Daily

on:
  schedule:
    - cron: '30 3 * * *'  # 每天 UTC 1:30 运行（对应亚洲时间约 09:30）
  workflow_dispatch:
jobs:
  send:
    name: Send LLM arXiv to Feishu
    runs-on: ubuntu-latest
    steps:
      - uses: junka/arxiv_feishu_bot_action@main
        with:
          keyword: 'LLM OR "large language model"'  # 设置筛选关键词
          webhook: ${{ secrets.FEISHU_BOT_WEBHOOK }}
          signkey: ${{ secrets.FEISHU_BOT_SIGNKEY }}
